### ISSUE TITLE
[q] configuing babel loader to process symlinked directories

### ISSUE THREAD

**Issue by vladp** [rjerue/craco-babel-loader#1]
I used to use rewire, but now migrating to latest react-scripts, threfore also hoping Craco can help.

within ./src folder I have a numer of subdirectories that are symbolic links to other locations outside of the ./src

I think I have setup craco to do all the things I did with rewire before
a)  add aliases (so that I can refer in `import` to various directories outside ./src by aliases)

b) instruct babel loader to look into those paths to transplat (and I also use react-vector-icons, so that also requires babel to translant)

c) disable module scope plugin

However, I am getting an error I cannot seem to figure out...
npm run build   causes
**Cannot find module: 'react'. Make sure this package is installed.**

This error is coming from a file that is *not* in the ./src directory, but instead, from a file a
./src/wc.src/Somefile.js
where ./src/wc.src is a symlink to a directory above the current project..

Of course, react and all the other packages are installed with npm.
So the error seems to indicate that the whole build system cannot figure out where **any** node_modules package is.

my config
```
const path = require('path');
const resolve = path.resolve;
const fs = require('fs'); 

const { whenDev, paths } = require('@craco/craco');
const rewireBabelLoader = require('craco-babel-loader');

// helpers
const appWorkspaceDirectory = fs.realpathSync(process.cwd());
const resolveAppWorkspaceDir = (relativePath) => {return path.resolve(appWorkspaceDirectory, relativePath);};

/* physical (after symlinks are resolved) */
const pathsToMySourcesArr = [
  fs.realpathSync(paths.appNodeModules + '/react-native-vector-icons'),
  fs.realpathSync(paths.appSrc + '/js.app'), //<- symlink to ../../../rn.common/src/js.app
  fs.realpathSync(paths.appSrc + '/app.src'),//<- symlink
  fs.realpathSync(paths.appSrc + '/wc.src')  //<- symlink
];

module.exports = {
  webpack: {
    alias: {
      web_common: path.resolve('./src/wc.src'),
      app_src: path.resolve('./src/app.src'),
      rnjs_common: path.resolve('./src/js.app')
    }
  },
  plugins: [
    {
      plugin: rewireBabelLoader,
      options: {
        includes: pathsToMySourcesArr,
        excludes: [/(node_modules|bower_components)/] //things you want to exclude here
      }
    },

    //this is my own inline plugin to get rid of ModuleScope Plugin
    {
      plugin: {
        overrideWebpackConfig: ({ webpackConfig, cracoConfig, pluginOptions, context: { env, paths } }) => {
          let newWebPackConfig=Object.assign({},webpackConfig);
          const guessedIdxOfModuleScopePlugin=1;
          //remove it
          newWebPackConfig.resolve.plugins.splice(guessedIdxOfModuleScopePlugin,1); 
          return newWebPackConfig;
        },
    }
  ],

  devServer: whenDev(() => ({
    https: {
      cert: fs.readFileSync('something.cer'),
      key: fs.readFileSync('something.pkcs8'),
      passphrase: 'somephrase'
    }
  }))

};

```

thank you

**Comment by rjerue** [comment]
Hey,

This is difficult to debug without any sort of package.json, or more preferably a test repo where this can be reproduced. You're also using CRACO with lots of different settings, so it's difficult to isolate it.

The error that your receiving is because webpack can not find the react module.

I made this plugin initially so that I could use it with a monorepo via yarn. If you're importing things from outside of your src folder, you may want to try that.

**Comment by vladp** [comment]
ok, thank you.
will ponder over it some more
