### ISSUE TITLE
Bump patch version

### ISSUE THREAD

**Issue by jswhetstone** [rjerue/craco-babel-loader#3]
Just ran into this, I need @craco/craco ^5.0.0, and I see that you updated the dependency, but the yarn registry is still returning the previous version of code, presumably because the package version hasn't changed from 0.1.2 
https://github.com/rjerue/craco-babel-loader/blob/59e7a10d9e1dadcb805ecefcfc80dda00f88493f/package.json#L3

**Comment by rjerue** [comment]
@jswhetstone give it another try

**Comment by jswhetstone** [comment]
Looks good, thanks.
