### ISSUE TITLE
It does not work with webpack 5

### ISSUE THREAD

**Issue by AntonioRedondo** [rjerue/craco-babel-loader#6]
Hello there,

I'm trying to use this loader with the below CRACO configuration

```javascript
const path = require('path');
const fs = require('fs');

const cracoBabelLoader = require('craco-babel-loader');

const appDirectory = fs.realpathSync(process.cwd());
const resolvePackage = relativePath => path.resolve(appDirectory, relativePath);

module.exports = {
  webpack: {
    alias: {
      '@components': path.resolve(__dirname, 'src/components')
    },
    plugins: [
      {
        plugin: cracoBabelLoader,
        options: {
          includes: [
            resolvePackage('../state')
          ],
        },
      },
    ],
  },
};
```

But when executing `craco start` I get the below error:

```bash
$ npm start

> project@0.1.0 start
> craco start

Failed to compile.

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.plugins[0] misses the property 'apply'.
   function
   -> The run point of the plugin, required method.
```

Create React App 4 uses webpack 5. And I suspect this is the reason for this error as it seems `craco-babel-loader` is not ready for this version of webpack.

This happening with:
- `create-react-app`: 4.0.3
- `@craco/craco`:  6.4.1
- `craco-babel-loader`:  0.1.4

**Comment by rjerue** [comment]
Hey @AntonioRedondo, thanks for reporting. I'll try to take a look at this in the next few days. Error is likely because this is from prior version of webpack and it's interface with babel-loader has changed.

**Comment by rjerue** [comment]
I was able to reproduce the error message, but I think it's a config issue as opposed to an issue with this plugin.`plugins` is its own key as opposed to one that lives under `webpack`.

Does it work if you do the following?

```js
const path = require("path");
const fs = require("fs");

const cracoBabelLoader = require("craco-babel-loader");

const appDirectory = fs.realpathSync(process.cwd());
const resolvePackage = (relativePath) =>
  path.resolve(appDirectory, relativePath);

module.exports = {
  webpack: {
    alias: {
      "@components": path.resolve(__dirname, "src/components"),
    },
  },
  plugins: [
    {
      plugin: cracoBabelLoader,
      options: {
        includes: [resolvePackage("../state")],
      },
    },
  ],
};

```

**Comment by AntonioRedondo** [comment]
Oh gosh, what a dumb mistake... Closing the issue. Thanks for the quick response!

**Comment by rjerue** [comment]
No worries! This actually encouraged me to clean up this repo a bit!
