### ISSUE TITLE
Craco 7 support?

### ISSUE THREAD

**Issue by mennovanhout** [rjerue/craco-babel-loader#9]
Currently you can't instull this using Craco 7 and CRA 5.

**Comment by rjerue** [comment]
Taking a look!

**Comment by rjerue** [comment]
CRACO 7 is currently in alpha. I will upgrade (and/or be open to PRs that update) once it is stable.

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/4666313/173846581-250a2851-5c88-480d-925a-aea8b089b422.png">

**Comment by mennovanhout** [comment]
I understand problem is that the latest version of crete-react-app only works with v7 alpha of craco and then this loader doesn't work.

I already made my own babel loader atm so I leave to you what you want to di with it, just wanted to let you know it is now impossible to use this package with a brand new create-react-app

**Comment by frudolph77** [comment]
craco v7 is released since about two weeks.

**Comment by rjerue** [comment]
Hey, thanks for the heads up. I don't use this actively for anything professionally. I'll will update when I get some free time. Also would be happy to accept a PR that does

**Comment by rjerue** [comment]
It looks like the final version of craco 7 worked out of the box in the test app included w/ this repo. I updated some of the tooling in the repo and published a version to prevent a semver warning. https://github.com/rjerue/craco-babel-loader/releases/tag/v1.0.4

Please let me know if there's any problems + provide an example.
